### ISSUE TITLE
[Request] Compatibility with illagers wear armor

### ISSUE THREAD

**Issue by Xvareon** [SebSemos/F.M.R.P-Freshly-Modded-#20] opened 2024-12-07 04:07 UTC
https://modrinth.com/mod/illagers-wear-armor

**Comment by DarthCaesium** [comment] 2024-12-10 18:21
This is a duplicate of https://github.com/SebSemos/F.M.R.P-Freshly-Modded-/issues/12, so please close your issue down.

**Comment by Xvareon** [comment] 2024-12-14 18:19
Got it.

**Closed as completed** 2024-12-14 18:20 UTC
